context:
  cache: true
  strict: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "./schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "./schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
gleaner:
  mill: false
  runid: iow
  summon: true
summoner:
    after: ""
    delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1)
    # will headless, the name of the container "service" work
    #headless: http://headless:9222
    headless: http://localhost:9222
    mode: full
    threads: 5
millers:
  graph: true
minio:
  address: localhost
  port: 9000
  ssl: false
  accessKey: amazingaccesskey
  secretKey: amazingsecretkey
  bucket: mybucket
sources:
- active: 'true'
  domain: https://geoconnex.us
  headless: 'false'
  name: counties0
  pid: https://gleaner.io/genid/geoconnex
  propername: counties0
  sourcetype: sitemap
  url: https://geoconnex.us/sitemap/ref/counties/counties__0.xml
