---
title: "create-bulk-files"
format: html
editor: visual
---

## Reference Features

Set up a function that procures the list of PIDs, goes to each PID, downloads the JSON LD, concatenates them into one collection per collection, etc.

```{r}
options(scipen = 999)
accept_jsonld <- httr::add_headers("Accept" = "application/ld+json")

get_jsonld <-
  function(url) {
    x <- httr::GET(url, config = accept_jsonld)
    if(x$status_code == 200) {
      x <- rawToChar(x$content)
    } else {
      x <- ""
    }
    return(x)
    
  }

get_oaf_jsonld <- function(url, 
                           collection,
                           limit = 1000,
                           skip = 0,
                           uri_field = "uri",
                           out = paste0(collection,".","jsonld")) {
  
  l <- unlist(jsonlite::fromJSON(paste0(url, 
                                 "/collections/", 
                                 collection, 
                                 "/items?skipGeometry=true&limit=",
                                 limit,"&offset=",skip))$features$properties[uri_field])
  
  l <- parallel::mclapply(l, get_jsonld, mc.cores=8)
  l2 <- paste(unlist(l),collapse=",\n")
  l3 <- paste0("[\n",l2,"\n]")
  l4 <- gsub(",\n,",",",l3)
  write(l4, out)
  print(paste0(out, " is written"))
}

url = "https://reference.geoconnex.us"
collection = "hu02"

get_oaf_jsonld(url = url, collection = "hu02")

get_oaf_jsonld(url = url, collection = "hu04")
get_oaf_jsonld(url = url, collection = "hu06", limit = 10000)
get_oaf_jsonld(url = url, collection = "hu08")

get_oaf_jsonld(url = url, collection = "states")

get_oaf_jsonld(url = url, collection = "counties")


get_oaf_jsonld(url = url, collection = "nat_aq")

get_oaf_jsonld(url = url, collection = "principal_aq")

get_oaf_jsonld(url = url, collection = "sec_hydrg_reg")


get_oaf_jsonld(url = url, collection = "counties", limit=10000)
get_oaf_jsonld(url = url, collection = "hu08", limit=10000)

for(i in 17:34) {
get_oaf_jsonld(url = url, collection = "mainstems", skip=(i-1)*1000, out=paste0("mainstems",i,".jsonld"))
}

for(i in 107:187) {
get_oaf_jsonld(url = url, collection = "gages", skip=(i-1)*1000, out=paste0("gages",i,".jsonld"))
}
```

## WQP

```{r}
#| echo: false
2 * 2
```

## NWIS Surface

## NWIS Ground

## WaDE normal

## WaDE NLDI

## New Mexico
